version: "3.8"

services:
  eth-listener:
    build: ../eth-listener
    container_name: eth-listener
    restart: unless-stopped
    environment:
      - API_KEY_ETHERSCAN=6437IIBSEYIIZ77Z7GAG43U81VDTQM57YQ
      - ETHEREUM_RPC_URL=https://ethereum-sepolia-rpc.publicnode.com  # RPC Público da Sepolia
      - ETHEREUM_WS_URL=wss://ethereum-sepolia-rpc.publicnode.com  # WS Público da Sepolia
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=eth-transactions
      - CONTRACT_ADDRESS=0xd47B84cD828538eE33264911E117e3557af39231
    networks:
      - eth-net
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - eth-net
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - eth-net

networks:
  eth-net:
    driver: bridge
