// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Gustavo P Gialluisi",
            "url": "http://www.fdqf.com",
            "email": "atendimento@fdqf.com.br"
        },
        "license": {
            "name": "FDQF License",
            "url": "http://license.fdqf.com.br"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alunocursoitemmodulos/{id}": {
            "get": {
                "description": "Get AlunoCursoItemModulo by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursoitemmodulos"
                ],
                "summary": "Busca um único item de módulo de uma matrícula",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "AlunoCursoItemModulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update AlunoCursoItemModulo by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursoitemmodulos"
                ],
                "summary": "Atualiza progresso, status ou campos específicos do item de módulo",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "AlunoCursoItemModulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos para atualização",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AlunoCursoItemModuloUpdateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunocursos": {
            "get": {
                "description": "Find all alunoCursos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursos"
                ],
                "summary": "Find all alunoCursos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Insert or Update a alunoCurso",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursos"
                ],
                "summary": "Save a alunoCurso",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "alunoCurso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunocursos/{id}": {
            "get": {
                "description": "Get a alunoCurso by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursos"
                ],
                "summary": "Get a alunoCurso pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "alunoCurso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Insert or Update a alunoCurso",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursos"
                ],
                "summary": "Save a alunoCurso",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "alunoCurso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a alunoCurso by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursos"
                ],
                "summary": "Delete a alunoCurso pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "alunoCurso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunocursos/{id}/itemmodulos": {
            "get": {
                "description": "Get all AlunoCursoItemModulo by AlunoCurso ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursoitemmodulos"
                ],
                "summary": "Lista todos os itens de módulo de uma matrícula",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "AlunoCurso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunos": {
            "get": {
                "description": "Find all alunos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunos"
                ],
                "summary": "Find all alunos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Insert an Aluno",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunos"
                ],
                "summary": "Save a aluno",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "aluno ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunos/by-wallet/{id}": {
            "get": {
                "description": "Get a aluno by wallet address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunos"
                ],
                "summary": "Get a aluno pela sua wallet",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "aluno ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunos/{id}": {
            "get": {
                "description": "Get a aluno by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunos"
                ],
                "summary": "Get a aluno pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "aluno ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Insert or Update a aluno",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunos"
                ],
                "summary": "Save a aluno",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "aluno ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a aluno by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunos"
                ],
                "summary": "Delete a aluno pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "aluno ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunos/{parent}/cursos": {
            "get": {
                "description": "Get cursos do aluno by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursos"
                ],
                "summary": "Get cursos do aluno pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "aluno ID",
                        "name": "parent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cursos": {
            "get": {
                "description": "Find all cursos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cursos"
                ],
                "summary": "Find all cursos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Insert or Update a curso",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cursos"
                ],
                "summary": "Save a curso",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "curso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cursos/{id}": {
            "get": {
                "description": "Get a curso by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cursos"
                ],
                "summary": "Get a curso pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "curso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Insert or Update a curso",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cursos"
                ],
                "summary": "Save a curso",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "curso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a curso by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cursos"
                ],
                "summary": "Delete a curso pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "curso ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cursos/{parent}/alunos": {
            "get": {
                "description": "Get alunos do curso by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alunocursos"
                ],
                "summary": "Get alunos do curso pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "curso ID",
                        "name": "parent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cursos/{parent}/modulos": {
            "get": {
                "description": "Get modulos da curso by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modulos"
                ],
                "summary": "Get modulos da curso pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "curso ID",
                        "name": "parent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/itens/{id}": {
            "get": {
                "description": "Retrieve an item modulo by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itemmodulo"
                ],
                "summary": "Get item modulo by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ItemModulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemModuloOutputDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an item from a modulo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itemmodulo"
                ],
                "summary": "Update item modulo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ItemModulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated item",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ItemModuloInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemModuloOutputDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an item modulo by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itemmodulo"
                ],
                "summary": "Delete item modulo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ItemModulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/itens/{id}/mover": {
            "post": {
                "description": "Change the order of an item modulo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itemmodulo"
                ],
                "summary": "Move item modulo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ItemModulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Action (cima|baixo|inicio|fim)",
                        "name": "action",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/modulos": {
            "post": {
                "description": "Insert a modulo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modulos"
                ],
                "summary": "Save a modulo",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "modulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/modulos/{id}": {
            "get": {
                "description": "Get a modulo by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modulos"
                ],
                "summary": "Get a modulo pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "modulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Insert or Update a modulo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modulos"
                ],
                "summary": "Save a modulo",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "modulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a modulo by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modulos"
                ],
                "summary": "Delete a modulo pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "modulo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/modulos/{modulo_id}/itens": {
            "get": {
                "description": "Retrieve all items from a given modulo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itemmodulo"
                ],
                "summary": "Get all items from a modulo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Modulo ID",
                        "name": "modulo_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ItemModuloOutputDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create an item in a modulo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itemmodulo"
                ],
                "summary": "Create item modulo",
                "parameters": [
                    {
                        "description": "ItemModulo input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ItemModuloInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ItemModuloOutputDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pessoas": {
            "get": {
                "description": "Get pessoas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pessoas"
                ],
                "summary": "Get pessoas",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/users/generate_token": {
            "post": {
                "description": "Get a user JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user JWT",
                "parameters": [
                    {
                        "description": "user credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.AlunoCursoItemModuloUpdateDTO": {
            "type": "object",
            "properties": {
                "blockchain_rede_validacao": {
                    "type": "string"
                },
                "blockchain_tx_envio": {
                    "type": "string"
                },
                "endereco_contrato_validar": {
                    "type": "string"
                },
                "progresso": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/entity.TipoStatusItemModulo"
                },
                "status_validacao_contrato": {
                    "$ref": "#/definitions/entity.TipoStatusValidacaoContrato"
                },
                "tempo_assistido": {
                    "type": "integer"
                }
            }
        },
        "dto.ItemModuloAulaDTO": {
            "type": "object",
            "properties": {
                "texto": {
                    "type": "string"
                }
            }
        },
        "dto.ItemModuloContractValidationDTO": {
            "type": "object",
            "properties": {
                "endereco_contrato": {
                    "type": "string"
                },
                "rede": {
                    "type": "string"
                }
            }
        },
        "dto.ItemModuloInputDTO": {
            "type": "object",
            "properties": {
                "aula": {
                    "$ref": "#/definitions/dto.ItemModuloAulaDTO"
                },
                "contract_validation": {
                    "$ref": "#/definitions/dto.ItemModuloContractValidationDTO"
                },
                "descricao": {
                    "type": "string"
                },
                "estimativa_tempo_minutos": {
                    "type": "integer"
                },
                "modulo_id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "video": {
                    "$ref": "#/definitions/dto.ItemModuloVideoDTO"
                }
            }
        },
        "dto.ItemModuloOutputDTO": {
            "type": "object",
            "properties": {
                "aula": {
                    "$ref": "#/definitions/dto.ItemModuloAulaDTO"
                },
                "contract_validation": {
                    "$ref": "#/definitions/dto.ItemModuloContractValidationDTO"
                },
                "created_at": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "estimativa_tempo_minutos": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "modulo_id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "ordem": {
                    "type": "integer"
                },
                "tipo": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "video": {
                    "$ref": "#/definitions/dto.ItemModuloVideoDTO"
                }
            }
        },
        "dto.ItemModuloVideoDTO": {
            "type": "object",
            "properties": {
                "video_url": {
                    "type": "string"
                }
            }
        },
        "entity.TipoStatusItemModulo": {
            "type": "string",
            "enum": [
                "não iniciado",
                "em andamento",
                "concluído"
            ],
            "x-enum-varnames": [
                "TipoStatusItemModuloNaoIniciado",
                "TipoStatusItemModuloEmAndamento",
                "TipoStatusItemModuloConcluido"
            ]
        },
        "entity.TipoStatusValidacaoContrato": {
            "type": "string",
            "enum": [
                "validação contrato pendente",
                "validação contrato concluída",
                "validação contrato erro"
            ],
            "x-enum-varnames": [
                "TipoStatusValidacaoContratoPendente",
                "TipoStatusValidacaoContratoConcluido",
                "TipoStatusValidacaoContratoErro"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "FDQF - Microserviço de Cursos",
	Description:      "Microserviço modelo para cadastro de cursos",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
